/*GENERATED BY OBNC 0.13.3*/

#include <obnc/OBNC.h>
#include <obnc/Out.h>

int main(int argc, char *argv[])
{
	OBNC_Initialize(argc, argv);
	Out_Init();
	Out_String_("hellow, world", 14);
	Out_Ln_();
	return 0;
}
